### ISSUE TITLE
葉っぱが入るプランター"Pot"を作る．

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#1]
Prefab"Pot"を作成してください．
- [x] add-potブランチで作業
- [x] 保存場所はAssets/Scenes/MainGame．
- [x] Potは当たり判定のコンポーネントCollisionを持ちます．
- [x] Potは物理演算のコンポーネントRigidBodyを持ちます．
- [x] 大きさは0.5 * 0.5 * 0.5でお願いします．

**Comment by Zaslon** [comment]
potについての疑問点
 - 植木鉢のみで0.5 * 0.5 * 0.5？
 - 草が生えたモデルを作る場合，「草と植木鉢」で1モデルか，「草」と「植木鉢」で2モデルか？

**Comment by tanitta** [comment]
- 植木鉢のみで0.5x0.5x0.5でお願いします．
- 植木鉢だけのモデルで，草は別のGameObjectをUnity上で組み合わせます．

**Comment by Zaslon** [comment]
単純に同一位置に配置すれば植木鉢に植わるように作ります．

**Comment by tanitta** [comment]
- [x] @HoshiUmeko さん，3Dモデルのprefabへの組み込みお願いします！その変更確認できたらmergeします
