### ISSUE TITLE
Unityのビルドがコケる

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#116]
ビルド時に以下のエラーを出力して失敗する．
```
Mesh doesn't have albedo UVs. Please create them in your modelling package. UnityEditor.BuildPlayerWindow:BuildPlayerAndRun()
```
以下の対処法でfixできそうです．
[Blenderで作ったモデルがUnityでベイクできない](http://nn-hokuson.hatenablog.com/entry/2017/02/01/193716)

**Comment by Zaslon** [comment]
- [x] ポット
- [x] きのこ
- [x] はっぱ
- [x] プレイヤー
- [x] 葉っぱキャノン
- [x] 葉っぱキャノン王冠
- [x] 葉っぱキャノン土台
- [x] 葉っぱキャノンたま
- [x] 売人
- [x] 売人車
- [x] 畑
- [x] 畝
- [x] 井戸
- [x] 街頭
- [x] 家A（正方形）
- [x] 家B（長方形）
- [x] 家C（L字）
- [x] 小さい家
- [x] 小さい長い家
- [x] ドラム缶（障害物）
- [x] ベンチ（障害物）
- [x] ただの木（障害物）
- [x] テーブル
- [x] 椅子
- [x] テレビとテレビ台
- [x] 貯水タンク
- [x] ゴミ箱
- [x] 貯水塔
- [x] 田舎の謎風車
- [x] 有刺鉄線
- [x] 脚立
- [x] 室外機
- [x] ゴミの塊
- [x] クソでかいメリケンゴミ箱
- [x] ポリスメン
- [x] 浮浪者
- [x] ラリラリアイコン
- [x] ピヨリング
- [x] バット
- [x] 懐中電灯
