### ISSUE TITLE
ゲームオーバー

### ISSUE THREAD

**Issue by OtObOx** [ld40-team-unagi/main-game#15]
【詳細】
ゲームオーバーの条件
- [ ] ポリ公または浮浪者が主人公に密着したら負け。（耐久力があってもポリ公に職質された時点で負け）
- [ ] 手を染めた状態で種とポットの数が0になったら負け
判定後ホワイトアウトしていってbankrupt表示
クリックするとタイトル画面へ遷移する
■必要な機能
- [x] 文字表示（bankrupt）←意味は倒産
- [x] 判定後ホワイトアウト
- [x] クリックするとタイトル画面へ遷移
■必要なリソース
- [ ] 文字
- [x] 判定時のSE

**Comment by HoshiUmeko** [comment]
「クリックするとタイトル画面へ遷移」

**Comment by HoshiUmeko** [comment]
「クリックするとタイトル画面へ遷移」
画面をどこでもクリックしたらタイトル画面へ遷移という認識で問題ないですか？

**Comment by tanitta** [comment]
とりあえず問題ないです！お願いします．

**Comment by tanitta** [comment]
#124 に引き継ぎます
