### ISSUE TITLE
🌿🍄ヤバいブツのGameObjectを作る🍄🌿

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#2]
- [x] add-yabaブランチで作業 
- [x] きのこと葉っぱのモデルを作ってください
- [x] 両方Assets/Scenes/MainGameに保存してください
- [x] 当たり判定無し
- [x] 大きさは0.5x1.0x0.5
- [x] 見た目は草の底面が原点になるようにしてください

**Comment by Zaslon** [comment]
- 草の成長段階は，完成形ですか？
- 草はプランターと同位置に置くつもりですか？（プランターに隠れる部分の茎長さ0.5を確保すべきですか？）

**Comment by tanitta** [comment]
草の成長段階はとりあえず完成形でお願いします．成長過程の演出はextra successでいきましょう．
プランターに隠れる部分の0.25（プランタの大きさの半分）の長さ追加をお願いします．
