### ISSUE TITLE
フィールドの仕様

### ISSUE THREAD

**Issue by OtObOx** [ld40-team-unagi/main-game#37]
【詳細】
フィールドを鬼ごっこする仕様になりましたので以下のオブジェクトが必要です。
■必要な機能
- [x] 家の中に入ると屋根が開き、中を直上から見下ろす形にする
- [x] フィールドではカメラはTPS視点（主人公の後ろ）
■必要なリソース
- [x] 街頭
- [x] 家A（正方形）
- [x] 家B（長方形）
- [x] 家C（L字）
- [x] ドラム缶（障害物）
- [x] ベンチ（障害物）
- [x] ただの木（障害物）←初期ツリーでいいかも

フィールド上のオブジェクトが増えると華やかな見た目になるけど、
劇的に重くなるのでこんな感じ？
余裕があれば適当な障害物を入れてもいいかもしれない。
家の大きさは正方形の場合10mx10m
これを基準に家B,Cの作成をお願いします

**Comment by Zaslon** [comment]
- 壁の厚みは0.5m
- 家の大きさは内側サイズで計測
- 家の中の家具
 - [x] テーブル
 - [x] ソファ→椅子に変更
 - [x] テレビとテレビ台
- 賑やかし設置物
 - [x] 貯水タンク
 - [x] ゴミ箱
 - [x] 貯水塔
 - [x] 田舎の謎風車

**Comment by Zaslon** [comment]
プレハブの追加
- [x] 街灯
- [x] ドラム缶（障害物）
- [x] ベンチ（障害物）
- [x] ただの木（障害物)
- [x] テーブル
- [x] 椅子
- [x] テレビとテレビ台
- [x] 貯水タンク
- [x] ゴミ箱
- [x] 田舎の謎風車

**Comment by OtObOx** [comment]
すべて実装できましたので閉じます
