### ISSUE TITLE
敵を追加

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#4]
【詳細】
敵
# 必要な機能
- [x] 敵は主人公に向かって進んでくる。
- [ ] 売人には行かない
- [ ] 敵出現位置は一か所ではなく四方八方ランダム
- [ ] 敵は葉っぱキャノンの玉に当たるとラリってるアイコンを
　敵の頭上に表示してふらふらしながらMAP外に出る
- [ ] 敵巡回中の足音
- [ ] 敵が走って迫ってくるときの足音

# 必要なリソース
- [x] ポリスメン
- [x] 浮浪者
- [x] ラリラリアイコン。虹がかかってて蝶々が飛んでる感じ
モデルは動物をモチーフに。
- [ ] 敵巡回中の足音
- [ ] 敵が走って迫ってくるときの足音

# 警察と浮浪者の区別
- [x] 警察はプレイヤーに向かってくる
~~- [ ] 浮浪者もプレイヤーに向かってくる~~

**Comment by OtObOx** [comment]
必要なもの
敵
ポリスメン
浮浪者？

3種類欲しい

**Comment by Zaslon** [comment]
- それぞれの大きさの指定はありますか？なければ人は慎重1.8mで適当に作ります．
- 「敵」は何をする存在ですか？プレイヤーを倒すのか，生産物を奪うのか，施設を破壊するのか．
- 浮浪者の役割は？

**Comment by Zaslon** [comment]
- それぞれの大きさの指定はありますか？なければ人は慎重1.8mで適当に作ります．
- 「敵」は何をする存在ですか？プレイヤーを倒すのか，生産物を奪うのか，施設を破壊するのか．
- 浮浪者の役割は？

**Comment by OtObOx** [comment]
人物の大きさに具体的な数値はありません。1.8mで良いと思います。
・敵によって違う動きをさせたい（といいなぁ）
・ポリスメンはパトカーで乗り付けて職質。
・浮浪者は建築物またはプレイヤーを倒しにくる

**Comment by Zaslon** [comment]
add enemy ブランチを設けます．

**Comment by Zaslon** [comment]
警察，浮浪者，ドローンの3種にするつもりですがいいですか？

**Comment by OtObOx** [comment]
問題ありません。

**Comment by OtObOx** [comment]
仕様変更はいります。

■必要な機能

 敵は主人公に向かって進んでくる。
 売人には行かない
 敵出現位置は一か所ではなく四方八方ランダム
 無くなります。→売人が出現すると沸かなくなる。（それまでに沸いた敵はそのまま攻めてくる）
 敵は葉っぱキャノンの玉に当たるとラリってるアイコンを
　敵の頭上に表示してふらふらしながらMAP外に出る

↓
敵は主人公に向かって進んでくる。
売人には行かない
敵出現位置は一か所ではなく四方八方ランダム（MAP外から？）
 敵は葉っぱキャノンの玉に当たるとラリってるアイコンを
敵の頭上に表示してふらふらしながらMAP外に出る

**Comment by Zaslon** [comment]
虹を追加したが，虹だけだと可理解性に疑問があるので，はっぱと蝶が回転するピヨピヨリングも並行して追加した．

**Comment by OtObOx** [comment]
機能とリソース増えました。
