### ISSUE TITLE
ゲームプレイ中のBGMを追加する

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#45]
- [x] prefabの名前:                   MainGameBGM
- [x] 保存場所:                           Assets/Scenes/MainGame/
- [x] 音声データの場所:              Assets/Scenes/MainGame/MainGameBGM.<なんらかの拡張子>
- [x] **音声データのmetadata**:     Assets/Scenes/MainGame/MainGameBGM.<なんらかの拡張子>.meta
- [x] 常になっている環境音
BGMを内蔵したAudio SourceのPrefabをAssetとして追加してください．

**Comment by OtObOx** [comment]
仕様変更はいります。
常になっている環境音を追加します。
（BGMが二つという認識です。）

**Comment by OtObOx** [comment]
実装できたので閉じます。
