### ISSUE TITLE
オープニング（Title画面）のBGMの追加

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#46]
- [ ] prefabの名前:                   BGM
- [ ] 保存場所:                           Assets/Scenes/TitleGame/
- [x] 音声データの場所:              Assets/Scenes/TitleGame/BGM.<なんらかの拡張子>
- [x] **音声データのmetadata**:     Assets/Scenes/TitleGame/BGM.<なんらかの拡張子>.meta

BGMを内蔵したAudio SourceのPrefabをAssetとして追加してください．

#47 終わったのでokです．
~~このissueはシーンTitleをAssets/Scenes/TitleGameに移動するissue #47 がcloseされた後に着手してください．~~

**Comment by OtObOx** [comment]
実装完了したので閉じます
