### ISSUE TITLE
GameOver時のBGMの追加

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#48]
- [ ] prefabの名前:                   GameOverBGM
- [ ] 保存場所:                           Assets/Scenes/GameOver/
- [x] 音声データの場所:              Assets/Scenes/GameOver/BGM.<なんらかの拡張子>
- [x] **音声データのmetadata**:     Assets/Scenes/GameOver/BGM.<なんらかの拡張子>.meta

BGMを内蔵したAudio SourceのPrefabをAssetとして追加してください．

#47 終わったのでokです．
~~このissueはシーンGameOverをAssets/Scenes/GameOverに移動するissue #47 がcloseされた後に着手してください．~~

**Comment by OtObOx** [comment]
実装確認したので閉じます
