### ISSUE TITLE
ゲームの説明文を考える

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#93]

**Comment by Zaslon** [comment]
Don't bug me!

I did it! I got seeds of millionaire!
My bro said me only I should do is clickin'.
Make it rain!


[2:14] 
邪魔するな！

やったぜ！億万長者の種を手に入れた！
俺のダチはただクリックすれば良いって言ってたな．
金の雨降らせてやるぜ！

**Comment by OtObOx** [comment]
ありがとうございます。
たにったさんが責任をもって反映してくれます。
