### ISSUE TITLE
チュートリアル用のオブジェクト

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#94]
@Zaslon さんが帰ってくるまでに操作方法まとめておきます．看板とかでいい感じにお願いします:)

**Comment by Zaslon** [comment]
書くべきこと
- WASD・上下左右で移動
- マウスホイールでズームイン・アウト
- 左クリックで設置（スペースバージョンへの差し替えも可）
- 右クリックで拾う
- 葉っぱの成長について
- 売人が売人としてわかるように
