### ISSUE TITLE
プレイヤーが葉っぱをもってるときはプレイヤーの背中にはっぱ袋を表示させる．

### ISSUE THREAD

**Issue by tanitta** [ld40-team-unagi/main-game#97]
- [x] はっぱ袋のスケールは持っている葉っぱの数cropYieldの量に比例して大きくなるようにしてください．
- [x] 葉っぱの量でプレイヤーの足が遅くなる用にしてください

**Comment by HoshiUmeko** [comment]
きのこを収穫したときはどうしますか　葉っぱ袋とは別のほうがいいですか
